# kubectl --namespace kube-system create serviceaccount tiller
# kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
# kubectl --namespace kube-system patch deploy tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
#
# OR THET BUT ITS NOT FULL
# kubectl delete -f https://raw.githubusercontent.com/9474757/Jenkinsfiles/master/EKS/FIX_forbidden_TILLER_serviceaccount.yaml
# kubectl apply -f https://raw.githubusercontent.com/9474757/Jenkinsfiles/master/EKS/FIX_forbidden_TILLER_serviceaccount.yaml
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
