#!/bin/sh

kubectl create serviceaccount tiller-def
kubectl create clusterrolebinding tiller \
  --clusterrole=cluster-admin \
  --serviceaccount=default:tiller-def
helm init --service-account tiller-def
helm init --service-account tiller-def \
--tiller-image 
helm init --tiller-namespace default --tiller-service-account tiller-def
